"""Build and cache the aligned RTH cross-asset panel + the rule-9a data-quality report.

    python -u -m futures.nq.claude_exploration_1.scripts.build_panel

Writes ``artifacts/panel_<legs>.parquet`` and ``reports/DATA_QUALITY.md``. Every study
in this project loads the cache rather than rebuilding, so all arms provably run on
identical rows.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

from ..core import data as D

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"
REP = ROOT / "reports"

LEGSETS = {"4leg": D.DXY_LEGS, "5leg": D.DXY_LEGS_5, "eur": D.DXY_LEGS_EUR}


def path_for(tag: str) -> Path:
    return ART / f"panel_{tag}.parquet"


def load(tag: str = "4leg") -> pd.DataFrame:
    p = path_for(tag)
    if not p.exists():
        raise FileNotFoundError(f"{p} missing -- run scripts.build_panel first")
    return pd.read_parquet(p)


def main(tags=("4leg", "5leg", "eur")) -> None:
    ART.mkdir(parents=True, exist_ok=True)
    REP.mkdir(parents=True, exist_ok=True)
    texts = []
    for tag in tags:
        panel, cov = D.rth_panel(legs=LEGSETS[tag])
        panel.to_parquet(path_for(tag), index=False)
        txt = f"\n## Basket `{tag}` = {list(LEGSETS[tag])}\n\n```\n" \
              + D.coverage_report(panel, cov) + "\n```\n"
        texts.append(txt)
        print(f"[{tag}] wrote {path_for(tag)}  rows={len(panel):,}")
    hdr = (
        "# Data quality (rule 9a)\n\n"
        "Generated by `scripts/build_panel.py`. One row per equity-RTH minute\n"
        "(09:30-16:00 ET) for every near-complete, non-degraded session on the ES\n"
        "calendar. Prices are roll-adjusted log levels; the dollar index is the\n"
        "published ICE geometric basket rebuilt from CME FX futures.\n\n"
        "Read the staleness tables before any cross-asset claim: forward-filled\n"
        "minutes manufacture autocorrelation and fake lead-lag, which are precisely\n"
        "the effects this project measures.\n"
    )
    (REP / "DATA_QUALITY.md").write_text(hdr + "".join(texts), encoding="utf-8")
    print(f"wrote {REP / 'DATA_QUALITY.md'}")


if __name__ == "__main__":
    main(tuple(sys.argv[1:]) or ("4leg", "5leg", "eur"))
